# Generated by Django 6.0 on 2025-12-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle",
            name="summary",
        ),
    ]
